name: Dapper CI on PR and Merge
run-name: CI on Merge to ${{ github.repository }}

on:
  pull_request:
  push:
    tags: '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: rancher/dapper:v0.6.0
    permissions:
      contents: read
    steps:
      - name: Fix the not-a-git-repository issue
        run: |
          apk -U add git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
            go-version-file: go.mod
      - name: build with Dapper
        run: dapper ci
      - name: LS the bin
        run: ls -lR output/bin